version: "3"

services:
  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus-svc
    ports:
      - "9090:9090"
    command: --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./prometheus:/etc/prometheus

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    ports:
      - "3003:3000"
    environment:
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus