{
 "title": "Grafana Dashboard",
 "time": { "from": "now-10m", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_usage{job='api-tracking'}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RAM Memory Used (%)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ram_usage_pct{job='api-tracking'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ram Used (GB)",
   "type": "stat",
   "gridPos": { "x": 16, "y": 0, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "GB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ram_usage_gb{job='api-tracking'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sanic_request_latency_sec_sum{job='api-tracking'}[2m]) / rate(sanic_request_latency_sec_count{job='api-tracking'}[2m])",
     "legendFormat": "Request Duration",
     "alias": "Request Duration",
     "color": "Request Duration"
    }
   ]
  },
  {
   "title": "Request per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(sanic_request_count_total{job='api-tracking'}[2m])",
     "legendFormat": "Request per Second",
     "alias": "Request per Second",
     "color": "Request per Second"
    }
   ]
  }
 ]
}